# Generated by Django 2.2.6 on 2019-11-14 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameOfThrones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='casa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GameOfThrones.Casa'),
        ),
        migrations.AddField(
            model_name='personaje',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='personaje',
            name='temporadas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GameOfThrones.Temporada'),
        ),
    ]
