# Generated by Django 2.2.6 on 2019-11-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameOfThrones', '0002_auto_20191114_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='casa',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='temporadas',
        ),
    ]
