# Generated by Django 2.2.6 on 2019-11-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameOfThrones', '0003_auto_20191114_2037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personaje',
        ),
    ]
