# Generated by Django 2.2.6 on 2019-11-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameOfThrones', '0005_personaje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personaje',
        ),
    ]
