# Generated by Django 2.2.6 on 2019-11-14 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameOfThrones', '0008_delete_personaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('imagen', models.URLField(max_length=225, verbose_name='imagen')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameOfThrones.Casa')),
                ('temporadas', models.ManyToManyField(to='GameOfThrones.Temporada')),
            ],
        ),
    ]
