# Generated by Django 2.2.6 on 2019-11-14 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameOfThrones', '0009_personaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='casa',
        ),
        migrations.DeleteModel(
            name='Casa',
        ),
    ]
