# Generated by Django 2.2.6 on 2019-11-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameOfThrones', '0013_auto_20191115_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
