# Generated by Django 2.2.6 on 2019-11-15 11:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameOfThrones', '0014_auto_20191115_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
    ]
