# Generated by Django 2.2.6 on 2019-11-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameOfThrones', '0016_auto_20191115_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_temporada', models.IntegerField()),
                ('num_episodios', models.IntegerField()),
                ('imagen', models.URLField(max_length=225, verbose_name='imagen')),
            ],
        ),
        migrations.AddField(
            model_name='personaje',
            name='temporadas',
            field=models.ManyToManyField(to='GameOfThrones.Temporada'),
        ),
    ]
