# Generated by Django 2.2.6 on 2019-11-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameOfThrones', '0017_auto_20191115_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='temporadas',
            field=models.ManyToManyField(related_name='tempo', to='GameOfThrones.Temporada'),
        ),
    ]
