# Generated by Django 2.2.6 on 2019-11-17 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameOfThrones', '0018_auto_20191117_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempo', to='GameOfThrones.Casa'),
        ),
    ]
